### ISSUE TITLE
Missing names of individuals who agree to adhere to the guide

### ISSUE THREAD

**Issue by griffinh1** [aubreypc/cs203-S2019-conduct#19]
Missing names of individuals who agree to adhere to the guide. There are new branches merged to master but their names are not added to the bottom.

**Comment by quigley-c** [comment]
I opened a new PR for everyone to add their names to. #20

**Comment by shafferz** [comment]
This issue has been made obsolete by the switch to a Slack-based signature collection. Thank you, though!
