### ISSUE TITLE
Unfinished bullet point and other formatting issues

### ISSUE THREAD

**Issue by everitt-andrew** [aubreypc/cs203-S2019-conduct#21]
Under the acceptable behavior in the deadline section, a bullet point that begins with, "Grade yourself based..." seems to be unfinished. Could the group that was responsible for it add the necessary information?

**Comment by everitt-andrew** [comment]
Also the deadlines section appears to be missing the semicolons following the "acceptable behavior" and "unacceptable behavior" headers

**Comment by reibelj** [comment]
To add on, for the Acceptable Conduct section it is labeled as (A), I believe it should be (C)

**Comment by barrezuetai** [comment]
@ursowilliam @ElisiaW

**Comment by everitt-andrew** [comment]
And the bullet points for the section seem to be off compared to the others.

**Comment by quigley-c** [comment]
I've created a new PR for this. #24

**Comment by quigley-c** [comment]
Looks like @shafferz addressed this issue in his PR #32 and has merged.
