### ISSUE TITLE
Some spelling & grammar changes

### ISSUE THREAD

**Issue by aubreypc** [aubreypc/cs203-S2019-conduct#27]
Issues from https://github.com/Allegheny-Computer-Science-203-S2019/cs203-S2019-conduct/pull/13#pullrequestreview-197881200

> In the "Attendance" section you capitalize the word "Labs". Did you intend to capitalize this word?

> Instead of writing "we will be defining" could you more simply write "we define"?

> There is at least one part of the guide that uses "that" to refer to a person. I suggest that we standardize on using "who" to refer to people.

> It also seems that there are some slight differences in the way in which you format content. Sometimes phrases or labels are in bold and/or italics and other times they are not. Can this be made more consistent?

> A similar point could be made for the formatting of certain words. For instance, do you prefer to write Slack or Slack or slack or slack?

> There are a few places in the guide where the spacing is not exactly correct. For instance, I think that if you are going to have first/second you should write "first/second" and not "first/ second" or "first /second"

**Comment by aubreypc** [comment]
Issues from https://github.com/Allegheny-Computer-Science-203-S2019/cs203-S2019-conduct/pull/13#pullrequestreview-197883314

> There are instances of: "Team Members shall", "Team Members shall NOT", "Members shall", "No member shall", and "No Team Lead Shall". You should pick a standard for these.

> There are also some issues related to inconsistency with bullets and indentation that need addressed.

(see link for line by line comments)

**Comment by shafferz** [comment]
Alex did a good job finishing this issue off with PR #43. Thanks!
