### ISSUE TITLE
Open questions about style

### ISSUE THREAD

**Issue by aubreypc** [aubreypc/cs203-S2019-conduct#28]
Issues from https://github.com/Allegheny-Computer-Science-203-S2019/cs203-S2019-conduct/pull/13#pullrequestreview-197881200

> There is at least one part of the guide that uses "that" to refer to a person. I suggest that we standardize on using "who" to refer to people.

**Comment by barrezuetai** [comment]
Did we fix this issue? @shafferz

**Comment by chenc-allegheny** [comment]
I can do this, but I only see one in deadline Acceptable Behavior (C)

**Comment by shafferz** [comment]
We did fix this issue @barrezuetai, thanks for mentioning me! Closed.
