### ISSUE TITLE
Include definition of "postmortem"?

### ISSUE THREAD

**Issue by aubreypc** [aubreypc/cs203-S2019-conduct#29]
Issue from https://github.com/Allegheny-Computer-Science-203-S2019/cs203-S2019-conduct/pull/13#pullrequestreview-197881200

> Do you think that everyone will understand the meaning of the word "postmortem"? This word has a generally accepted meaning and then a specific meaning in the context of software. Is there a way that you could clarify this matter with, say, an extra phrase or example?

**Comment by shafferz** [comment]
This was fixed in a PR. Thank you!
