### ISSUE TITLE
Document Format Standardization

### ISSUE THREAD

**Issue by shafferz** [aubreypc/cs203-S2019-conduct#30]
Distinct from issues #21 , #28 , and #27 , I think the entire `conduct.md` should be standardized to feel coherent and maintain document integrity. Some issues noticed:

* Not all lists follow the same format.
* Not all lists are nested the same way for similarly-formatted lists.
* The sections below the list of sections should be in the same order as the list of sections itself (For example, Conduct should come before Attendance)

Once we have standardized the document, it would be easier to make the changes raised in previous issues (and may, in some cases, resolve parts of them).

**Comment by aubreypc** [comment]
Great points. For the list syntax and nesting, is there some kind of linter/auto-fixer for markdown that we could configure to ensure things are standardized? Or maybe we could write a script & run it with Travis so the build fails if things are inconsistent?
