### ISSUE TITLE
Ambiguous Unacceptable Behavior in Decisions

### ISSUE THREAD

**Issue by shafferz** [aubreypc/cs203-S2019-conduct#31]
I have a question about the language used in the Decisions category of `conduct.md`. In the document, the following is what is listed as Unacceptable (U) Behavior for decisions-related conduct:

> * **Unacceptable (U):**
>   * Making decisions without notifying team members.
>   * Question the decision after it is made.
>   * Making a decision based on only popular opinion.

I think the point "Question the decision after it is made" is rather ambiguous. Does this mean we shouldn't disregard decisions that have been made at our discretion? Or does this mean that once a decision is made we cannot call it further into question with our Technical Leads or the instructor if we still do not agree? I'm not sure exactly what it is saying.

I also don't fully understand "Making a decision based on only popular opinion." Does this mean we should (And perhaps this could be listed as an Acceptable Behavior (C), of which there are currently none listed) consult our team before making a decision even if most people seem to agree? Does this also mean we should wait until official decisions have been made before taking any actions?

I just want to clear these questions up, and perhaps improve the language of the section to remove ambiguity about the meanings of these points. I think it might also help to have a list of some Acceptable Behaviors (C) as other categories have, to make the intent more clear. As written, I am not currently comfortable signing to pledge to this iteration of the Conduct Guide without further clarification.

**Comment by shafferz** [comment]
I added @griffinh1 and @enpuyou as assignees, as I believe this was your team's issue initially, and I wanted to bring you guys in on the conversation first. What do you guys think?

**Comment by enpuyou** [comment]
Thanks for pointing that out. For the part `Question the decision after it is made`, our first intuition on this is that everyone should just speak out their concerns on decisions openly before they are made; and it won't be a good idea to complain about it after unless it proves to be a totally wrong decision. I think that would undermine the execution of the decision, and also the trust between team members. I think we can phrase it more precisely. Let me know if you have any suggestion! Thanks!

**Comment by shafferz** [comment]
Hey @enpuyou, thanks for getting back to me! I think your ideas for Acceptable Behaviors and adding a new Unacceptable Behavior are great. For rewording the second Unacceptable Behavior, I would suggest something along the lines of:

> * Complaining about a decision after it has been agreed upon by the team(s) involved.

That way the intent of the point is more clear. 

Can you open a branch and make these fixes? I don't imagine it would take long, and when you're ready we can review a Pull Request of them. We really need to get moving on this project! Thank you!

**Comment by shafferz** [comment]
This issue was fixed in a PR.
