### ISSUE TITLE
Should We Remove the Signatures Section?

### ISSUE THREAD

**Issue by shafferz** [aubreypc/cs203-S2019-conduct#34]
@Michionlion suggested on the fork's pull request that we remove the Signatures section from `conduct.md` in favor of some alternate method that is easier for us to collect the signatures.

Do you guys think we should just collect signatures in a simple Word or Google Doc, and produce a `.pdf` file with our signatures? That way, we can include a `conduct-guide-signatures.pdf` of some sort with the files in the repository, and simply reference that document in the Conduct Guide.

The only drawback I see is a lack of ease for adding new signatures or removing signatures moving forward. What is your guys' thoughts on this? Feedback would be greatly appreciated.

**Comment by quigley-c** [comment]
I think having a separate file for signatures is a good idea, as it helps reduce clutter in the main document and allows us to easily check for signatures from team members. What kind of format do you think is best?

**Comment by shafferz** [comment]
> I think having a separate file for signatures is a good idea, as it helps reduce clutter in the main document and allows us to easily check for signatures from team members. What kind of format do you think is best?

After a little more thinking, I think the best way to collect the initial signatures is via Slack directly. From there, we can have one individual update the Signatures list. That way, if people wish to sign on to our code of conduct, we can add them with simple PRs in the future. 

I no longer think we should manage a separate document, though it can still be done. At this point, we should prioritize speed so that we can get this Conduct Guide shipped quickly.

**Comment by shafferz** [comment]
This issue was resolved in a Pull Request (#40).
